language: cpp
compiler: 
  - gcc
os:
  - linux
sudo: true

script:
  - sudo apt-get install libboost-test-dev -yy
  - mkdir -p build && cd build
  - cmake ..
  - make unittests
  - ctest -V
  - make openwith-cli
