language: cpp
compiler: 
  - gcc
os:
  - linux

addons:
  apt:
    packages:
    - libboost-test-dev

script:
  - mkdir -p build && cd build
  - cmake ..
  - make unittests
  - ctest -V
  - make openwith-cli
