name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [gcc, clang]
    env:
      CC: ${{ matrix.compiler }}
      CXX: ${{ matrix.compiler }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get -y install libboost-test-dev
    - name: Build library on ${{ matrix.os }} with ${{ matrix.compiler }}
      run: |
        cmake -B build -S . && cmake --build build --target mimeapps
    - name: Run unittests on ${{ matrix.os }} with ${{ matrix.compiler }}
      working-directory: build
      run: |
        cmake --build . --target unittests && ctest -V
    - name: Build example on ${{ matrix.os }} with ${{ matrix.compiler }}
      run: |
        cmake --build build --target openwith-cli
